@ECommerceOutdoor_HostAddress = http://localhost:5007

GET {{ECommerceOutdoor_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{ECommerceOutdoor_HostAddress}}/brand/get-all-brands

###
